version: '3.8'
services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=its_instrumentasi
      - DOCKER_INFLUXDB_INIT_BUCKET=electronic_nose
      # TAMBAHKAN BARIS INI:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=electronic_nose_token 
    restart: always

volumes:
  influxdb2-data:
  influxdb2-config: